# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
tone_instructions: "Talk like a pragmatic programmer, give information, give feedback, but no generic bullshit words, like 'streamlined' in every second sentence."
reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  sequence_diagrams: false
  auto_review:
    enabled: true
    drafts: true
