services:

  redis:
    image: redis

  postgres:
    image: quay.io/acoustid/postgresql:master
    volumes:
      - ./admin/ci/create_db.sql:/docker-entrypoint-initdb.d/10_create_db.sql
    environment:
      POSTGRES_USER: acoustid
      POSTGRES_PASSWORD: acoustid
      POSTGRES_DB: postgres

  nsqlookupd:
    image: nsqio/nsq
    command:
      - "/nsqlookupd"
    ports:
      - "127.0.0.1:4160:4160"
      - "127.0.0.1:4161:4161"

  nsqd:
    image: nsqio/nsq
    depends_on:
      - nsqlookupd
    command:
      - "/nsqd"
      - "--broadcast-address=nsqd"
      - "--lookupd-tcp-address=nsqlookupd:4160"
    ports:
      - "127.0.0.1:4150:4150"
      - "127.0.0.1:4151:4151"

  index:
    image: ghcr.io/acoustid/acoustid-index:v2022.02.03

  init-db:
    image: quay.io/acoustid/acoustid-server:latest
    build: .
    depends_on:
      - postgres
    command:
      - bash
      - -ecx
      - |
        /opt/acoustid/server/admin/docker/run-alembic.sh upgrade head
    env_file:
      - ./admin/dev/server.env
    profiles:
      - tools

  api:
    image: quay.io/acoustid/acoustid-server:latest
    build: .
    depends_on:
      - redis
      - postgres
      - index
    command:
      - /opt/acoustid/server/admin/docker/run-api.sh
    env_file:
      - ./admin/dev/server.env
    profiles:
      - frontend

  web:
    image: quay.io/acoustid/acoustid-server:latest
    build: .
    depends_on:
      - redis
      - postgres
      - index
    command:
      - /opt/acoustid/server/admin/docker/run-web.sh
    env_file:
      - ./admin/dev/server.env
    profiles:
      - frontend

  cron:
    image: quay.io/acoustid/acoustid-server:latest
    build: .
    depends_on:
      - redis
      - postgres
      - index
    command:
      - /opt/acoustid/server/admin/docker/run-cron.sh
    env_file:
      - ./admin/dev/server.env
    profiles:
      - backend

  worker:
    image: quay.io/acoustid/acoustid-server:latest
    build: .
    depends_on:
      - redis
      - postgres
      - index
    command:
      - /opt/acoustid/server/admin/docker/run-worker.sh
    env_file:
      - ./admin/dev/server.env
    profiles:
      - backend
