ARG IMAGE=quay.io/acoustid/acoustid-server
ARG VERSION=master
FROM ${IMAGE}:${VERSION}

EXPOSE 3032

HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -f http://localhost:3032/_health || exit 1

CMD ["/opt/acoustid/server/admin/run-web.sh"]
