# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from acoustid.proto.fpstore import fpstore_pb2 as fpstore_dot_fpstore__pb2


class FingerprintStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_unary(
                '/fpstore.FingerprintStore/Insert',
                request_serializer=fpstore_dot_fpstore__pb2.InsertFingerprintRequest.SerializeToString,
                response_deserializer=fpstore_dot_fpstore__pb2.InsertFingerprintResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/fpstore.FingerprintStore/Update',
                request_serializer=fpstore_dot_fpstore__pb2.UpdateFingerprintRequest.SerializeToString,
                response_deserializer=fpstore_dot_fpstore__pb2.UpdateFingerprintResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/fpstore.FingerprintStore/Delete',
                request_serializer=fpstore_dot_fpstore__pb2.DeleteFingerprintRequest.SerializeToString,
                response_deserializer=fpstore_dot_fpstore__pb2.DeleteFingerprintResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/fpstore.FingerprintStore/Get',
                request_serializer=fpstore_dot_fpstore__pb2.GetFingerprintRequest.SerializeToString,
                response_deserializer=fpstore_dot_fpstore__pb2.GetFingerprintResponse.FromString,
                )
        self.Search = channel.unary_unary(
                '/fpstore.FingerprintStore/Search',
                request_serializer=fpstore_dot_fpstore__pb2.SearchFingerprintRequest.SerializeToString,
                response_deserializer=fpstore_dot_fpstore__pb2.SearchFingerprintResponse.FromString,
                )
        self.Compare = channel.unary_unary(
                '/fpstore.FingerprintStore/Compare',
                request_serializer=fpstore_dot_fpstore__pb2.CompareFingerprintRequest.SerializeToString,
                response_deserializer=fpstore_dot_fpstore__pb2.CompareFingerprintResponse.FromString,
                )


class FingerprintStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FingerprintStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=fpstore_dot_fpstore__pb2.InsertFingerprintRequest.FromString,
                    response_serializer=fpstore_dot_fpstore__pb2.InsertFingerprintResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=fpstore_dot_fpstore__pb2.UpdateFingerprintRequest.FromString,
                    response_serializer=fpstore_dot_fpstore__pb2.UpdateFingerprintResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=fpstore_dot_fpstore__pb2.DeleteFingerprintRequest.FromString,
                    response_serializer=fpstore_dot_fpstore__pb2.DeleteFingerprintResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=fpstore_dot_fpstore__pb2.GetFingerprintRequest.FromString,
                    response_serializer=fpstore_dot_fpstore__pb2.GetFingerprintResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=fpstore_dot_fpstore__pb2.SearchFingerprintRequest.FromString,
                    response_serializer=fpstore_dot_fpstore__pb2.SearchFingerprintResponse.SerializeToString,
            ),
            'Compare': grpc.unary_unary_rpc_method_handler(
                    servicer.Compare,
                    request_deserializer=fpstore_dot_fpstore__pb2.CompareFingerprintRequest.FromString,
                    response_serializer=fpstore_dot_fpstore__pb2.CompareFingerprintResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fpstore.FingerprintStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FingerprintStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fpstore.FingerprintStore/Insert',
            fpstore_dot_fpstore__pb2.InsertFingerprintRequest.SerializeToString,
            fpstore_dot_fpstore__pb2.InsertFingerprintResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fpstore.FingerprintStore/Update',
            fpstore_dot_fpstore__pb2.UpdateFingerprintRequest.SerializeToString,
            fpstore_dot_fpstore__pb2.UpdateFingerprintResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fpstore.FingerprintStore/Delete',
            fpstore_dot_fpstore__pb2.DeleteFingerprintRequest.SerializeToString,
            fpstore_dot_fpstore__pb2.DeleteFingerprintResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fpstore.FingerprintStore/Get',
            fpstore_dot_fpstore__pb2.GetFingerprintRequest.SerializeToString,
            fpstore_dot_fpstore__pb2.GetFingerprintResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fpstore.FingerprintStore/Search',
            fpstore_dot_fpstore__pb2.SearchFingerprintRequest.SerializeToString,
            fpstore_dot_fpstore__pb2.SearchFingerprintResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Compare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fpstore.FingerprintStore/Compare',
            fpstore_dot_fpstore__pb2.CompareFingerprintRequest.SerializeToString,
            fpstore_dot_fpstore__pb2.CompareFingerprintResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
