# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/fingerprint.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63ommon/fingerprint.proto\x12\x06\x63ommon\".\n\x0b\x46ingerprint\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x0e\n\x06hashes\x18\x01 \x03(\rB5Z3github.com/acoustid/go-acoustid/proto/common;commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.fingerprint_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/acoustid/go-acoustid/proto/common;common'
  _globals['_FINGERPRINT']._serialized_start=36
  _globals['_FINGERPRINT']._serialized_end=82
# @@protoc_insertion_point(module_scope)
