"""more fields in submission

Revision ID: 661fce6a2f64
Revises: 0c79593066ed
Create Date: 2019-11-14 12:02:55.010214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '661fce6a2f64'
down_revision = '0c79593066ed'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_app():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_app():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_ingest():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('submission', sa.Column('application_id', sa.Integer(), nullable=True))
    op.add_column('submission', sa.Column('application_version', sa.String(), nullable=True))
    op.add_column('submission', sa.Column('foreignid', sa.String(), nullable=True))
    op.add_column('submission', sa.Column('format', sa.String(), nullable=True))
    op.add_column('submission', sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('submission', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('submission', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('submission_result', sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade_ingest():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_result', 'handled_at')
    op.alter_column('submission', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('submission', 'meta')
    op.drop_column('submission', 'handled_at')
    op.drop_column('submission', 'format')
    op.drop_column('submission', 'foreignid')
    op.drop_column('submission', 'application_version')
    op.drop_column('submission', 'application_id')
    op.drop_column('submission', 'account_id')
    # ### end Alembic commands ###


def upgrade_fingerprint():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_fingerprint():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
