"""add changes for new mbid merging logic

Revision ID: 6e49a33c60eb
Revises: b1a71d1125c2
Create Date: 2025-03-08 13:54:15.789054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e49a33c60eb'
down_revision = 'b1a71d1125c2'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_app():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_app():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_ingest():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_mbid_change', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('track_mbid_source', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade_ingest():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_mbid_source', 'updated')
    op.drop_column('track_mbid_change', 'updated')
    # ### end Alembic commands ###


def upgrade_fingerprint():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_mbid', sa.Column('merged_into', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('track_mbid_fk_merged_into'), 'track_mbid', 'track_mbid', ['merged_into'], ['id'])
    # ### end Alembic commands ###


def downgrade_fingerprint():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('track_mbid_fk_merged_into'), 'track_mbid', type_='foreignkey')
    op.drop_column('track_mbid', 'merged_into')
    # ### end Alembic commands ###
