"""add pending_submission table

Revision ID: 8953fd9f151a
Revises: ec9bf3e99852
Create Date: 2025-05-24 11:09:04.202245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8953fd9f151a'
down_revision = 'ec9bf3e99852'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_app():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_app():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_ingest():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pending_submission_pkey')),
    info={'bind_key': 'ingest'}
    )
    # ### end Alembic commands ###


def downgrade_ingest():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_submission')
    # ### end Alembic commands ###


def upgrade_fingerprint():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade_fingerprint():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
