"""disabled, merged_into for track_{puid,meta,foreignid}

Revision ID: 998c73cb216d
Revises: d7e8b1c80561
Create Date: 2025-03-22 08:26:30.264193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998c73cb216d'
down_revision = 'd7e8b1c80561'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_app():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_app():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_ingest():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade_ingest():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def upgrade_fingerprint():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_foreignid', sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('track_foreignid', sa.Column('merged_into', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('track_foreignid_fk_merged_into'), 'track_foreignid', 'track_foreignid', ['merged_into'], ['id'])
    op.add_column('track_meta', sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('track_meta', sa.Column('merged_into', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('track_meta_fk_merged_into'), 'track_meta', 'track_meta', ['merged_into'], ['id'])
    op.add_column('track_puid', sa.Column('disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('track_puid', sa.Column('merged_into', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('track_puid_fk_merged_into'), 'track_puid', 'track_puid', ['merged_into'], ['id'])
    # ### end Alembic commands ###


def downgrade_fingerprint():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('track_puid_fk_merged_into'), 'track_puid', type_='foreignkey')
    op.drop_column('track_puid', 'merged_into')
    op.drop_column('track_puid', 'disabled')
    op.drop_constraint(op.f('track_meta_fk_merged_into'), 'track_meta', type_='foreignkey')
    op.drop_column('track_meta', 'merged_into')
    op.drop_column('track_meta', 'disabled')
    op.drop_constraint(op.f('track_foreignid_fk_merged_into'), 'track_foreignid', type_='foreignkey')
    op.drop_column('track_foreignid', 'merged_into')
    op.drop_column('track_foreignid', 'disabled')
    # ### end Alembic commands ###
