"""add meta.created

Revision ID: d2176bc400c8
Revises: 661fce6a2f64
Create Date: 2019-12-02 07:14:01.145411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2176bc400c8'
down_revision = '661fce6a2f64'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_app():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_app():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_ingest():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_ingest():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_fingerprint():
    op.add_column(u'meta', sa.Column('created', sa.DateTime(timezone=True), nullable=True))


def downgrade_fingerprint():
    op.drop_column(u'meta', 'created')
