"""change submission length to int4

Revision ID: d7e8b1c80561
Revises: 468b44482655
Create Date: 2025-03-08 20:51:37.654499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7e8b1c80561'
down_revision = '468b44482655'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_app():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_app():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_ingest():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'length',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade_ingest():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission', 'length',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def upgrade_fingerprint():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_fingerprint():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
