"""add track_data

Revision ID: ec9bf3e99852
Revises: 6e49a33c60eb
Create Date: 2025-03-30 16:19:56.345673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9bf3e99852'
down_revision = '6e49a33c60eb'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_app():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_app():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_ingest():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_ingest():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_fingerprint():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fingerprint_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('gid', sa.UUID(), nullable=False),
        sa.Column('fingerprint', sa.LargeBinary(), nullable=False),
        sa.Column('simhash', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.ForeignKeyConstraint(['id'], ['fingerprint.id'], name=op.f('fingerprint_data_fk_id')),
        sa.PrimaryKeyConstraint('id', name=op.f('fingerprint_data_pkey')),
        info={'bind_key': 'fingerprint'}
    )
    op.create_index(op.f('fingerprint_data_idx_gid'), 'fingerprint_data', ['gid'], unique=True)
    op.create_index(op.f('fingerprint_data_idx_simhash'), 'fingerprint_data', ['simhash'], unique=False)
    # ### end Alembic commands ###


def downgrade_fingerprint():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('fingerprint_data_idx_simhash'), table_name='fingerprint_data')
    op.drop_index(op.f('fingerprint_data_idx_gid'), table_name='fingerprint_data')
    op.drop_table('fingerprint_data')
    # ### end Alembic commands ###
