CREATE OR REPLACE FUNCTION generate_api_key() RETURNS varchar
AS $$
    SELECT substring(regexp_replace(encode(decode(md5(current_timestamp::text || to_hex(ceil(random() * 16777215)::int)),'hex'),'base64'), '[/+=]', '', 'g') from 0 for 9);
$$ LANGUAGE 'SQL' IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION process_fp_query(int[]) RETURNS int[]
AS $$
    -- 627964279 is the sub-fingerprint generated by silence
    SELECT uniq($1) - 627964279;
$$ LANGUAGE 'SQL' IMMUTABLE STRICT;

--CREATE OR REPLACE FUNCTION process_fp_query(int[]) RETURNS int[]
--AS $$
--    -- 627964279 is the sub-fingerprint generated by silence
--    SELECT uniq(ARRAY(SELECT i & x'00ffffff'::int FROM unnest($1 - 627964279) i));
--$$ LANGUAGE 'SQL' IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION extract_fp_query(int[]) RETURNS int[]
AS $$
    SELECT process_fp_query(subarray($1, 200, 120));
$$ LANGUAGE 'SQL' IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION extract_short_fp_query(int[]) RETURNS int[]
AS $$
    SELECT process_fp_query(subarray($1, 0, 120));
$$ LANGUAGE 'SQL' IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION update_account_stats() RETURNS void
AS $$
DECLARE
    last_time timestamp with time zone;
    curr_time timestamp with time zone;
    rec record;
BEGIN
    SELECT last_updated INTO last_time FROM account_stats_control;
    SELECT max(created) INTO curr_time FROM submission;
    FOR rec IN SELECT so.account_id, count(*) AS count FROM submission su
        JOIN source so ON su.source_id = so.id
        WHERE last_time < su.created AND su.created <= curr_time
        GROUP BY so.account_id
    LOOP
        UPDATE account SET submission_count = submission_count + rec.count
        WHERE id = rec.account_id;
    END LOOP;
    UPDATE account_stats_control SET last_updated = curr_time;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION to_unsigned(int) RETURNS bigint
AS $$
    SELECT $1::bigint & x'ffffffff'::bigint;
$$ LANGUAGE 'SQL' IMMUTABLE STRICT;

